/* AZ-900 Study service worker (generated by scripts/sw-plugin.ts). */
const VERSION = '96468ed4f615'
const CACHE = 'az900-app-' + VERSION
const FONT_CACHE = 'az900-fonts'
const PRECACHE = ["./","./assets/ArcadePage-DLgov75K.js","./assets/BattlePage-JJ0cF9Zd.js","./assets/bosses-Bm-svZIU.js","./assets/content-BCMSnqwH.js","./assets/DrillPage-C-nt37nl.js","./assets/index-BW_Pic9z.js","./assets/index-Cy18YYOg.css","./assets/jsx-runtime-B4GHO8YW.js","./assets/LightningPage-D_2pE_aA.js","./assets/mixup-Cqrj2G2V.js","./assets/MixupPage-CPDUnsI2.js","./assets/PracticeRunner-Drhu_5gc.js","./assets/QuestionBrowserPage-BGaB9U0G.js","./assets/questions-QCTVMQIJ.js","./assets/QuestionView-S2wkbAoJ.js","./assets/QuestPage-Dsi7ivhZ.js","./assets/RaidPage-D_iy4Hmc.js","./assets/RegionPage-BCyT5HGS.js","./assets/WeakSpotsPage-CT15ehul.js","./favicon.svg","./icons/apple-touch-icon.png","./icons/icon-192.png","./icons/icon-512-maskable.png","./icons/icon-512.png","./manifest.webmanifest"]
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com']

self.addEventListener('install', (event) => {
  // Precache the whole app. A new version then WAITS (no skipWaiting here) until the page asks it to take over.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('az900-app-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (FONT_HOSTS.includes(url.hostname)) {
    // Fonts: serve from cache, refresh in the background (stale-while-revalidate).
    event.respondWith(
      caches.open(FONT_CACHE).then(async (cache) => {
        const hit = await cache.match(req)
        const fresh = fetch(req)
          .then((res) => {
            if (res.ok || res.type === 'opaque') cache.put(req, res.clone())
            return res
          })
          .catch(() => hit)
        return hit || fresh
      }),
    )
    return
  }
  if (url.origin !== self.location.origin) return
  if (req.mode === 'navigate') {
    // The app is a single page with hash routes: every navigation gets the cached page ('./') of THIS version.
    event.respondWith(caches.match('./', { cacheName: CACHE }).then((hit) => hit || fetch(req)))
    return
  }
  event.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)))
})
