/* Fabric Mill service worker (generated by scripts/sw-plugin.ts). */
const VERSION = '73115a74e633'
const CACHE = 'fabric-mill-' + VERSION
const PRECACHE = ["./","./assets/App-Bx0tatfh.js","./assets/Badges-DbOGXLFO.js","./assets/CodeBlock-DQyoEEbP.js","./assets/floors-BtKYn54U.js","./assets/fraunces-latin-opsz-normal-DihXLNYH.woff2","./assets/Glossary-C1anGoWS.js","./assets/index-DrqWJbDI.js","./assets/index-Dsdvrc5h.css","./assets/inter-latin-wght-normal-Dx4kXJAl.woff2","./assets/jsx-runtime-BguD1OXD.js","./assets/labs-DHgQeJFp.js","./assets/LabsPage-DUSb21QM.js","./assets/mock-DopitTe9.js","./assets/MockCenter-Dq-Z7mvb.js","./assets/MockExam-47qAEQMH.js","./assets/notes-Dz9Xhv7-.js","./assets/outline-BKiwKZEr.js","./assets/pairs-DsQhtYUz.js","./assets/PuzzlePanel-rY4QaFU4.js","./assets/puzzles-Bo6CYT8V.js","./assets/QuestionInput-DL-IcJ4k.js","./assets/questions-j0IYSdiS.js","./assets/questions-prepare-BF5b4L-q.js","./assets/react-CybPckBe.js","./assets/ReviewPage-Crp63oev.js","./assets/ReviewPage-DhvNtIA0.js","./assets/schema-C0G91WZ1.js","./assets/Settings-ClehRb-e.js","./assets/shuffle-CMjoR-Az.js","./assets/time-IawjHlSx.js","./assets/weak-Dp42ccOw.js","./assets/WeakSpots-rDD6joNx.js","./index.html","./favicon.svg","./icons/apple-touch-icon.png","./icons/icon-192.png","./icons/icon-512-maskable.png","./icons/icon-512.png","./manifest.webmanifest"]

self.addEventListener('install', (event) => {
  // Precache the whole app. A new version then WAITS (no skipWaiting here) until the page asks it to take over.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('fabric-mill-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return
  if (req.mode === 'navigate') {
    // A single-page app: every navigation gets the cached index.html of THIS version (offline too).
    event.respondWith(caches.match('./index.html', { cacheName: CACHE }).then((hit) => hit || fetch(req)))
    return
  }
  event.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)))
})
